language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="30ec78b4-599b-4e83-83b3-22b246c7868d"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -bogstepan@gmail.com
    on_success: never # default: change
    on_failure: always # default: always